name: Build and Update Image

on:
  push:
    branches: [main]

jobs:
  build-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: login Dockerhub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/node-app:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/node-app:${{ github.sha }}

      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          repository: suryasiddhart/action-manifests
          #token: ${{ secrets.TARGET_REPO_TOKEN }}
          #path: .


      - name: Update image tag in target repo
        run: |
          sed -i "s|image:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/node-app:${{ github.sha }}|" web-manifest.yaml

      - name: Commit and push changes
        run: |
          git config user.name "suryasiddhart"
          git config user.email "suryasiddhart@gmail.com"
          git add .
          git commit -m "Update image to ${{ secrets.DOCKERHUB_USERNAME }}/node-app"
          git push origin main